version: '3.8'

services:
  app:
    image: maxitwit/app
    build: ./
    container_name: maxitwit
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "127.0.0.1:5000:5000"
